spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/ai_exam?serverTimezone=GMT%2B8

mybatis:
  type-aliases-package: com.explore.pojo
  mapper-locations: mappers/*.xml